---
language: ruby
sudo: required
services:
  - docker
bundler_args: --without system_tests --full-index
before_install: rm Gemfile.lock || true
script: ["bundle exec rake test"]
rvm:
  - 2.4.1
env:
  - PUPPET_GEM_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.3.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.4.0" STRICT_VARIABLES=yes
matrix:
  include:
  # run acceptance tests on ubuntu-14.04
    - rvm: default 
      sudo: required
      services: docker
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set="ubuntu-14.04"
      script: bundle exec rake beaker
      bundler_args: --with acceptance
    - rvm: default
      sudo: required
      services: docker
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set="debian-7"
      script: bundle exec rake beaker
      bundler_args: --with acceptance
    - rvm: default
      sudo: required
      services: docker
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set="centos-7"
      script: bundle exec rake beaker
      bundler_args: --with acceptance
    - rvm: default
      sudo: required
      services: docker
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set="oraclelinux-7"
      script: bundle exec rake beaker
      bundler_args: --with acceptance
deploy:
  provider: puppetforge
  user: kschu91
  password:
    secure: NP6xKyc9Xjw8TJN5Yrw4epyHV1e+DwfNy0wHJZsxqvKXrxLJ576A5hS8u6tT3qyIFjcTdQyUnr++2R/YJFwoG6DgIJV9JpssHwY2iDxBvpAG/TKDMAL7IEZTSg4RNvTYA9rgK5eWNKqy5cV9U7Acem4sAP9tBOT9YzSpHOVeiIDU4mu5PAMEiYVqyfySCeVBCn04bd2X2LDeRasSVXMw1R+O2RzaGFCpBdKmcgXox+wCYGjq0AvPBPlP9QF5k8eiMP5Fwvm7s+9ErqGuhCrPzQ4RjGf3w6mGjMC5cZqclC9j130nb/+SlVJpQNRL3iF/R9Ogm5UCG5zWY/HG6cY+pL6NN+scGypX7DLMEXvNb2GAhoMxE78emdzmvCIHph1dkAejjh4xQtPIWU/8MgGKFfZ/wVmem+d/CvS8RFUqJ2isqs+XZkXeexsttgqOPetB7VsCTM8qkUu07AWpeRa3GF8bWQHPfSpS4gOgaQg0hAWwWHyqePMDW550vzuxx68l7vifY4L004H4n+NaeuzHxj1iDm0+iDMBjzGPo1Or0ZoW542a00L41aq1DQiFYyBHTLIlCmfD0YC7cUMJWilW1RTbg8OCZLlT6z9UgF5B1s04zOfjjCVye2bvwv19L1IUIH/VdFfMfMJcF1+FwHU89wDlaFB16MYefEeIfWDuwt0=
  on:
    tags: true
    # Only publish if our main Ruby target builds
    rvm: 2.4
    condition: $PUPPET_GEM_VERSION = "~> 5.4.0"
